### ISSUE TITLE
Invalid NaN value for viewing angle

### ISSUE THREAD

**Issue by jonas-eberle** [stactools-packages/sentinel2#101]
The viewing angle (zenith and azimuth) is being extracted from the granule metadata (MTD_TL.xml) and added to the assets. However, this information can be NaN instead of a float value.  

Current behaviour in this package is to convert it to float. This means a `not a number` value exported to JSON, which is invalid in JSON: 
```
"view:azimuth": NaN
```

Although I can store this with Python in JSON, other tools (e.g., pypgstac with orjson library) raise an exception. 

Example scene: 
`S2A_MSIL1C_20220218T112121_N0400_R037_T33WWT_20220218T133111.SAFE`
https://file.io/A2DByTDiWZUA (17 MB)

Example extract from `MTD_TL.xml`:
```
        <Mean_Viewing_Incidence_Angle bandId="0">
          <ZENITH_ANGLE unit="deg">NaN</ZENITH_ANGLE>
          <AZIMUTH_ANGLE unit="deg">NaN</AZIMUTH_ANGLE>
        </Mean_Viewing_Incidence_Angle>
        <Mean_Viewing_Incidence_Angle bandId="9">
          <ZENITH_ANGLE unit="deg">NaN</ZENITH_ANGLE>
          <AZIMUTH_ANGLE unit="deg">NaN</AZIMUTH_ANGLE>
        </Mean_Viewing_Incidence_Angle>
        <Mean_Viewing_Incidence_Angle bandId="10">
          <ZENITH_ANGLE unit="deg">NaN</ZENITH_ANGLE>
          <AZIMUTH_ANGLE unit="deg">NaN</AZIMUTH_ANGLE>
        </Mean_Viewing_Incidence_Angle>
        <Mean_Viewing_Incidence_Angle bandId="1">
          <ZENITH_ANGLE unit="deg">11.6740704215321</ZENITH_ANGLE>
          <AZIMUTH_ANGLE unit="deg">304.153705556385</AZIMUTH_ANGLE>
        </Mean_Viewing_Incidence_Angle>
        <Mean_Viewing_Incidence_Angle bandId="2">
          <ZENITH_ANGLE unit="deg">NaN</ZENITH_ANGLE>
          <AZIMUTH_ANGLE unit="deg">NaN</AZIMUTH_ANGLE>
        </Mean_Viewing_Incidence_Angle>

```

**Comment by philvarner** [comment]
example scene is here in RODA s3://sentinel-s2-l1c/tiles/33/W/WT/2022/2/18/0/
