### ISSUE TITLE
Don't use tileInfo.json

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/sentinel2#118]
From browsing https://github.com/sinergise/Sentinel2ProductIngestor, it looks like `tileInfo.json` is created by Singergise, _not_ provided by ESA. If possible, we should refactor this package to use the ESA metadata, e.g. `MTD_MSIL2A.xml`. 

Credit @matthewhanson for digging this up.

**Comment by matthewhanson** [comment]
tagging @gmilcinski to confirm that tileInfo.json (and productInfo.json) are created by Sinergise.

**Comment by gmilcinski** [comment]
Yep, confirmed. These two files are created by us.  
The original metadata (just renamed) is here:  
https://roda.sentinel-hub.com/sentinel-s2-l1c/tiles/1/K/AT/2018/7/20/0/metadata.xml

**Comment by gadomski** [comment]
Closing as invalid, `metadata_from_safe_manifest` already does this.
