### ISSUE TITLE
Major products upgrade upcoming from ESA

### ISSUE THREAD

**Issue by jonas-eberle** [stactools-packages/sentinel2#12]
Please be informed that there will be a products upgrade from ESA coming by the ~~end of October~~ January 2022 (see last comment): 
https://scihub.copernicus.eu/news/News00931

Relevant changes for the STAC creation that might be considered:

Sentinel-2 L1C: 
- Quality masks provided in raster format
- New Snow/ice mask
- Add DOI

Sentinel-2 L2A: 
- Provision of Band 01 at 20m spatial resolution: Band 01 will be added with 20m resolution (in the 20 m resolution image folder) in addition to the native 60m resolution.
- Addition of new Level-2A Quality Indicators
- Add DOI

Detailed information on the changes implemented are provided in dedicated sections of version 14.8 of the Products Specification Document (PSD) available [here](https://sentinels.copernicus.eu/documents/247904/685211/Sentinel-2-Products-Specification-Document-14_8.pdf). 

Sample products representative of Processing Baseline 04.00 will be made available in the coming days.

**Comment by matthewhanson** [comment]
The band offsets are added to the metadata now, along with scale and offset for each asset
