### ISSUE TITLE
Rename s2:granule_id to s2:tile_id

### ISSUE THREAD

**Issue by matthewhanson** [stactools-packages/sentinel2#127]
The `s2:granule_id` field is populated by the TILE_ID in the tile metadata.xml file.

See https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/50/C/NS/2020/12/S2A_50CNS_20201217_9_L2A/granule_metadata.xml

The S2 documentation is confusing, but while the word `granule` it is used interchangeably with `tile`.  It's also the name of a folder with a SAFE archive. All of the S2 Product specs use the term `tile`.   From the [S2 spec doc](https://sentinels.copernicus.eu/documents/247904/685211/S2-PDGS-TAS-DI-PSD-V14.9.pdf/3d3b6c9c-4334-dcc4-3aa7-f7c0deffbaf7?t=1643013091529):

```
The Sentinel-2 User Product is composed by a set of Granules, which are called Tiles
```

The field should be renamed to `s2:tile_id`.

**Comment by philvarner** [comment]
maybe add `s2:tile_id` (instead of replace) to maintain backward-compatibility with existing uses of `s2:granule_id`?

**Comment by matthewhanson** [comment]
I guess it depends on what the Sentinel-2 extension ends up on. We wouldn't be able to add any fields that weren't in there.
