### ISSUE TITLE
bbox for antimeridian-crossing scenes is incorrect

### ISSUE THREAD

**Issue by philvarner** [stactools-packages/sentinel2#149]
The scene in sentinel2/tests/data-files/S2A_MSIL2A_20230625T234621_N0509_R073_T01WCS_20230626T022157.SAFE/expected_output.json
represents an antimeridian-crossing scene. This is two multipolygons, on on each side of the antimeridian. This would ideally have a bbox with a SW longitude of about -179 and NE longitude of about 179. However, it actually has a bbox:

```
"bbox": [
    -179.93085,
    68.372483,
    180.0,
    69.394461
  ]
```

which both doesn't actually cover the longitude of the data, because it stops short to the west of -180. This also isn't the "inverse" longitude, which is a common mistake when an antimerdian-crossing polygon is misinterpreted as an incorrectly-wound polygon that spans nearly all longitude.

**Comment by przell** [comment]
Hi, thanks for this fix! 
Are the multipolygons created now valid conformin to [ST_IsValid](https://postgis.net/docs/using_postgis_dbmanagement.html#Valid_Geometry)? I guess they are sharing a line?
Here's an example where ST_IsValid fails on my side: https://stac.terrabyte.lrz.de/browser/collections/sentinel-2-c1-l2a/items/S2A_MSIL2A_20240319T230531_N0510_R044_T60UXG_20240320T013451
