### ISSUE TITLE
Request: Add sensor viewing angles to Sentinel-2 scene properties from STAC

### ISSUE THREAD

**Issue by lukasValentin** [stactools-packages/sentinel2#50]
We are currently using pystac-client to retrieve Sentinel-2 metadata (L2A) from Planetary computer, which used this repo to provide Sentinel STAC items.

While we found the mean solar azimuth angle (`s2:mean_solar_azimuth`) and mean solar zenith angle (`s2:mean_solar_zenith`) in the scene `properties`, the data about mean sensor azimuth and mean sensor zenith angle seems to be missing.

In our project, however, we'd require scene-wide angular information to run radiative transfer model simulations. In addition, we think that providing the entire angular data might be very helpful also for other users.

So, the proposal is to add the sensor azimuth and sensor zenith angle data as further entries to the scene properties. We are aware that the STAC specifications are undergoing, therefore, we'd are looking forward to your feedback and those from other Sentinel-2 users.

Thanks in advance.

**Comment by TomAugspurger** [comment]
Do you know which metadata file would have this information (granule, inspire, datastrip, ...)? And if so, do you know what key it would be under?

**Comment by lukasValentin** [comment]
It can be found in the GRANULE metadata file:

The xml tags are `<Mean_Sun_Angle>` and `<Mean_Viewing_Incidence_Angle_List>`, respectively. The sensor-angles are bit more complex since than the sun angles since these are provided per spectral band, so maybe they could be provided per band in STAC as well

**Comment by lukasValentin** [comment]
Thanks @TomAugspurger for the reply; indeed we are now using the workaround you proposed to obtain the angular information.
